knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"' # Ajoutez des guillemets
        options: []
    image:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"' # Ajoutez des guillemets
        options: []