nelmio_api_doc:
    documentation:
        info:
            title: "API Educo"
            description: "Documentation de l'API Educo"
            version: "1.0.0"
        servers:
            - url: "http://127.0.0.1:8000"
              description: "Serveur de développement"

    areas:
        path_patterns:
            - ^/user
